<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facilities</name>
   <tag></tag>
   <elementGuidId>2f091451-b9e9-46ca-9e5e-e6acadb21043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;INCLUSIONS&quot;]//*[contains(text(),&quot;${facility}&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;INCLUSIONS&quot;]//*[contains(text(),&quot;${facility}&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
