<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssignCarClick</name>
   <tag></tag>
   <elementGuidId>a230df76-9b9a-4252-a2e8-3f6f54dbb232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>
//*[@id=&quot;s2id_autogen7&quot;]/ul</value>
   </webElementProperties>
</WebElementEntity>
