<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectClick</name>
   <tag></tag>
   <elementGuidId>83649a3a-2f6f-44aa-9791-2f22d45b5374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='EXCLUSIONS']//*[@id='select_all']/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='EXCLUSIONS']//*[@id='select_all']/..</value>
   </webElementProperties>
</WebElementEntity>
