<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Country</name>
   <tag></tag>
   <elementGuidId>e1d1f68d-29d0-4ca3-9de4-fb5b49838cae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;select2-drop&quot;]//ul//li//div[text()=&quot;${CountryVariable}&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;select2-drop&quot;]//ul//li//div[text()=&quot;${CountryVariable}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
